// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template const_set_serializer.java
// Do not modify

package org.projectfloodlight.openflow.protocol.ver15;

import org.projectfloodlight.openflow.protocol.*;
import org.projectfloodlight.openflow.protocol.action.*;
import org.projectfloodlight.openflow.protocol.actionid.*;
import org.projectfloodlight.openflow.protocol.bsntlv.*;
import org.projectfloodlight.openflow.protocol.errormsg.*;
import org.projectfloodlight.openflow.protocol.meterband.*;
import org.projectfloodlight.openflow.protocol.instruction.*;
import org.projectfloodlight.openflow.protocol.instructionid.*;
import org.projectfloodlight.openflow.protocol.match.*;
import org.projectfloodlight.openflow.protocol.stat.*;
import org.projectfloodlight.openflow.protocol.oxm.*;
import org.projectfloodlight.openflow.protocol.oxs.*;
import org.projectfloodlight.openflow.protocol.queueprop.*;
import org.projectfloodlight.openflow.types.*;
import org.projectfloodlight.openflow.util.*;
import org.projectfloodlight.openflow.exceptions.*;
import org.projectfloodlight.openflow.protocol.OFBsnExtendedCapabilitiesConfigurability;
import java.util.Set;
import io.netty.buffer.ByteBuf;
import com.google.common.hash.PrimitiveSink;
import java.util.EnumSet;
import java.util.Collections;


public class OFBsnExtendedCapabilitiesConfigurabilitySerializerVer15 {

    public final static long BSN_EXT_CAP_CONFIGURABILITY_AN_DEFAULT_VAL = 0x1L;
    public final static long BSN_EXT_CAP_CONFIGURABILITY_AN_ENABLED_VAL = 0x2L;
    public final static long BSN_EXT_CAP_CONFIGURABILITY_AN_DISABLED_VAL = 0x4L;
    public final static long BSN_EXT_CAP_CONFIGURABILITY_FEC_DEFAULT_VAL = 0x8L;
    public final static long BSN_EXT_CAP_CONFIGURABILITY_FEC_ENABLED_VAL = 0x10L;
    public final static long BSN_EXT_CAP_CONFIGURABILITY_FEC_DISABLED_VAL = 0x20L;

    public static Set<OFBsnExtendedCapabilitiesConfigurability> readFrom(ByteBuf bb) throws OFParseError {
        try {
            return ofWireValue(bb.readLong());
        } catch (IllegalArgumentException e) {
            throw new OFParseError(e);
        }
    }

    public static void writeTo(ByteBuf bb, Set<OFBsnExtendedCapabilitiesConfigurability> set) {
        bb.writeLong(toWireValue(set));
    }

    public static void putTo(Set<OFBsnExtendedCapabilitiesConfigurability> set, PrimitiveSink sink) {
        sink.putLong(toWireValue(set));
    }


    public static Set<OFBsnExtendedCapabilitiesConfigurability> ofWireValue(long val) {
        EnumSet<OFBsnExtendedCapabilitiesConfigurability> set = EnumSet.noneOf(OFBsnExtendedCapabilitiesConfigurability.class);

        if((val & BSN_EXT_CAP_CONFIGURABILITY_AN_DEFAULT_VAL) != 0)
            set.add(OFBsnExtendedCapabilitiesConfigurability.BSN_EXT_CAP_CONFIGURABILITY_AN_DEFAULT);
        if((val & BSN_EXT_CAP_CONFIGURABILITY_AN_ENABLED_VAL) != 0)
            set.add(OFBsnExtendedCapabilitiesConfigurability.BSN_EXT_CAP_CONFIGURABILITY_AN_ENABLED);
        if((val & BSN_EXT_CAP_CONFIGURABILITY_AN_DISABLED_VAL) != 0)
            set.add(OFBsnExtendedCapabilitiesConfigurability.BSN_EXT_CAP_CONFIGURABILITY_AN_DISABLED);
        if((val & BSN_EXT_CAP_CONFIGURABILITY_FEC_DEFAULT_VAL) != 0)
            set.add(OFBsnExtendedCapabilitiesConfigurability.BSN_EXT_CAP_CONFIGURABILITY_FEC_DEFAULT);
        if((val & BSN_EXT_CAP_CONFIGURABILITY_FEC_ENABLED_VAL) != 0)
            set.add(OFBsnExtendedCapabilitiesConfigurability.BSN_EXT_CAP_CONFIGURABILITY_FEC_ENABLED);
        if((val & BSN_EXT_CAP_CONFIGURABILITY_FEC_DISABLED_VAL) != 0)
            set.add(OFBsnExtendedCapabilitiesConfigurability.BSN_EXT_CAP_CONFIGURABILITY_FEC_DISABLED);
        return Collections.unmodifiableSet(set);
    }

    public static long toWireValue(Set<OFBsnExtendedCapabilitiesConfigurability> set) {
        long wireValue = 0;

        for(OFBsnExtendedCapabilitiesConfigurability e: set) {
            switch(e) {
                case BSN_EXT_CAP_CONFIGURABILITY_AN_DEFAULT:
                    wireValue |= BSN_EXT_CAP_CONFIGURABILITY_AN_DEFAULT_VAL;
                    break;
                case BSN_EXT_CAP_CONFIGURABILITY_AN_ENABLED:
                    wireValue |= BSN_EXT_CAP_CONFIGURABILITY_AN_ENABLED_VAL;
                    break;
                case BSN_EXT_CAP_CONFIGURABILITY_AN_DISABLED:
                    wireValue |= BSN_EXT_CAP_CONFIGURABILITY_AN_DISABLED_VAL;
                    break;
                case BSN_EXT_CAP_CONFIGURABILITY_FEC_DEFAULT:
                    wireValue |= BSN_EXT_CAP_CONFIGURABILITY_FEC_DEFAULT_VAL;
                    break;
                case BSN_EXT_CAP_CONFIGURABILITY_FEC_ENABLED:
                    wireValue |= BSN_EXT_CAP_CONFIGURABILITY_FEC_ENABLED_VAL;
                    break;
                case BSN_EXT_CAP_CONFIGURABILITY_FEC_DISABLED:
                    wireValue |= BSN_EXT_CAP_CONFIGURABILITY_FEC_DISABLED_VAL;
                    break;
                default:
                    throw new IllegalArgumentException("Illegal enum value for type OFBsnExtendedCapabilitiesConfigurability in version 1.5: " + e);
            }
        }
        return wireValue;
    }

}
