// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template of_factory_class.java
// Do not modify

package org.projectfloodlight.openflow.protocol.ver15;

import org.projectfloodlight.openflow.protocol.*;
import org.projectfloodlight.openflow.protocol.action.*;
import org.projectfloodlight.openflow.protocol.actionid.*;
import org.projectfloodlight.openflow.protocol.bsntlv.*;
import org.projectfloodlight.openflow.protocol.errormsg.*;
import org.projectfloodlight.openflow.protocol.meterband.*;
import org.projectfloodlight.openflow.protocol.instruction.*;
import org.projectfloodlight.openflow.protocol.instructionid.*;
import org.projectfloodlight.openflow.protocol.match.*;
import org.projectfloodlight.openflow.protocol.stat.*;
import org.projectfloodlight.openflow.protocol.oxm.*;
import org.projectfloodlight.openflow.protocol.oxs.*;
import org.projectfloodlight.openflow.protocol.queueprop.*;
import org.projectfloodlight.openflow.types.*;
import org.projectfloodlight.openflow.util.*;
import org.projectfloodlight.openflow.exceptions.*;


public class OFInstructionIdsVer15 implements OFInstructionIds {
    public final static OFInstructionIdsVer15 INSTANCE = new OFInstructionIdsVer15();




    public OFInstructionIdApplyActions applyActions() {
        return OFInstructionIdApplyActionsVer15.INSTANCE;
    }

    public OFInstructionIdBsnArpOffload bsnArpOffload() {
        return OFInstructionIdBsnArpOffloadVer15.INSTANCE;
    }

    public OFInstructionIdBsnAutoNegotiation bsnAutoNegotiation() {
        return OFInstructionIdBsnAutoNegotiationVer15.INSTANCE;
    }

    public OFInstructionIdBsnDeny bsnDeny() {
        return OFInstructionIdBsnDenyVer15.INSTANCE;
    }

    public OFInstructionIdBsnDhcpOffload bsnDhcpOffload() {
        return OFInstructionIdBsnDhcpOffloadVer15.INSTANCE;
    }

    public OFInstructionIdBsnDisableL3 bsnDisableL3() {
        return OFInstructionIdBsnDisableL3Ver15.INSTANCE;
    }

    public OFInstructionIdBsnDisableSplitHorizonCheck bsnDisableSplitHorizonCheck() {
        throw new UnsupportedOperationException("OFInstructionIdBsnDisableSplitHorizonCheck not supported in version 1.5");
    }

    public OFInstructionIdBsnDisableSrcMacCheck bsnDisableSrcMacCheck() {
        return OFInstructionIdBsnDisableSrcMacCheckVer15.INSTANCE;
    }

    public OFInstructionIdBsnDisableVlanCounters bsnDisableVlanCounters() {
        return OFInstructionIdBsnDisableVlanCountersVer15.INSTANCE;
    }

    public OFInstructionIdBsnHashSelect bsnHashSelect() {
        return OFInstructionIdBsnHashSelectVer15.INSTANCE;
    }

    public OFInstructionIdBsnInternalPriority bsnInternalPriority() {
        return OFInstructionIdBsnInternalPriorityVer15.INSTANCE;
    }

    public OFInstructionIdBsnNdpOffload bsnNdpOffload() {
        return OFInstructionIdBsnNdpOffloadVer15.INSTANCE;
    }

    public OFInstructionIdBsnPacketOfDeath bsnPacketOfDeath() {
        return OFInstructionIdBsnPacketOfDeathVer15.INSTANCE;
    }

    public OFInstructionIdBsnPermit bsnPermit() {
        return OFInstructionIdBsnPermitVer15.INSTANCE;
    }

    public OFInstructionIdBsnPrioritizePdus bsnPrioritizePdus() {
        return OFInstructionIdBsnPrioritizePdusVer15.INSTANCE;
    }

    public OFInstructionIdBsnRequireVlanXlate bsnRequireVlanXlate() {
        return OFInstructionIdBsnRequireVlanXlateVer15.INSTANCE;
    }

    public OFInstructionIdBsnSpanDestination bsnSpanDestination() {
        return OFInstructionIdBsnSpanDestinationVer15.INSTANCE;
    }

    public OFInstructionIdClearActions clearActions() {
        return OFInstructionIdClearActionsVer15.INSTANCE;
    }

    public OFInstructionIdGotoTable gotoTable() {
        return OFInstructionIdGotoTableVer15.INSTANCE;
    }

    public OFInstructionIdMeter meter() {
        throw new UnsupportedOperationException("OFInstructionIdMeter not supported in version 1.5");
    }

    public OFInstructionIdWriteActions writeActions() {
        return OFInstructionIdWriteActionsVer15.INSTANCE;
    }

    public OFInstructionIdWriteMetadata writeMetadata() {
        return OFInstructionIdWriteMetadataVer15.INSTANCE;
    }

    public OFInstructionIdStatTrigger statTrigger() {
        return OFInstructionIdStatTriggerVer15.INSTANCE;
    }

    public OFMessageReader<OFInstructionId> getReader() {
        return OFInstructionIdVer15.READER;
    }


    public OFVersion getVersion() {
            return OFVersion.OF_15;
    }
}
