// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template const_set_serializer.java
// Do not modify

package org.projectfloodlight.openflow.protocol.ver15;

import org.projectfloodlight.openflow.protocol.*;
import org.projectfloodlight.openflow.protocol.action.*;
import org.projectfloodlight.openflow.protocol.actionid.*;
import org.projectfloodlight.openflow.protocol.bsntlv.*;
import org.projectfloodlight.openflow.protocol.errormsg.*;
import org.projectfloodlight.openflow.protocol.meterband.*;
import org.projectfloodlight.openflow.protocol.instruction.*;
import org.projectfloodlight.openflow.protocol.instructionid.*;
import org.projectfloodlight.openflow.protocol.match.*;
import org.projectfloodlight.openflow.protocol.stat.*;
import org.projectfloodlight.openflow.protocol.oxm.*;
import org.projectfloodlight.openflow.protocol.oxs.*;
import org.projectfloodlight.openflow.protocol.queueprop.*;
import org.projectfloodlight.openflow.types.*;
import org.projectfloodlight.openflow.util.*;
import org.projectfloodlight.openflow.exceptions.*;
import org.projectfloodlight.openflow.protocol.OFTableFeatureFlag;
import java.util.Set;
import io.netty.buffer.ByteBuf;
import com.google.common.hash.PrimitiveSink;
import java.util.EnumSet;
import java.util.Collections;


public class OFTableFeatureFlagSerializerVer15 {

    public final static int INGRESS_TABLE_VAL = 0x1;
    public final static int EGRESS_TABLE_VAL = 0x2;
    public final static int FIRST_EGRESS_VAL = 0x10;

    public static Set<OFTableFeatureFlag> readFrom(ByteBuf bb) throws OFParseError {
        try {
            return ofWireValue(bb.readInt());
        } catch (IllegalArgumentException e) {
            throw new OFParseError(e);
        }
    }

    public static void writeTo(ByteBuf bb, Set<OFTableFeatureFlag> set) {
        bb.writeInt(toWireValue(set));
    }

    public static void putTo(Set<OFTableFeatureFlag> set, PrimitiveSink sink) {
        sink.putInt(toWireValue(set));
    }


    public static Set<OFTableFeatureFlag> ofWireValue(int val) {
        EnumSet<OFTableFeatureFlag> set = EnumSet.noneOf(OFTableFeatureFlag.class);

        if((val & INGRESS_TABLE_VAL) != 0)
            set.add(OFTableFeatureFlag.INGRESS_TABLE);
        if((val & EGRESS_TABLE_VAL) != 0)
            set.add(OFTableFeatureFlag.EGRESS_TABLE);
        if((val & FIRST_EGRESS_VAL) != 0)
            set.add(OFTableFeatureFlag.FIRST_EGRESS);
        return Collections.unmodifiableSet(set);
    }

    public static int toWireValue(Set<OFTableFeatureFlag> set) {
        int wireValue = 0;

        for(OFTableFeatureFlag e: set) {
            switch(e) {
                case INGRESS_TABLE:
                    wireValue |= INGRESS_TABLE_VAL;
                    break;
                case EGRESS_TABLE:
                    wireValue |= EGRESS_TABLE_VAL;
                    break;
                case FIRST_EGRESS:
                    wireValue |= FIRST_EGRESS_VAL;
                    break;
                default:
                    throw new IllegalArgumentException("Illegal enum value for type OFTableFeatureFlag in version 1.5: " + e);
            }
        }
        return wireValue;
    }

}
