// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template of_virtual_class.java
// Do not modify

package org.projectfloodlight.openflow.protocol.ver15;

import org.projectfloodlight.openflow.protocol.*;
import org.projectfloodlight.openflow.protocol.action.*;
import org.projectfloodlight.openflow.protocol.actionid.*;
import org.projectfloodlight.openflow.protocol.bsntlv.*;
import org.projectfloodlight.openflow.protocol.errormsg.*;
import org.projectfloodlight.openflow.protocol.meterband.*;
import org.projectfloodlight.openflow.protocol.instruction.*;
import org.projectfloodlight.openflow.protocol.instructionid.*;
import org.projectfloodlight.openflow.protocol.match.*;
import org.projectfloodlight.openflow.protocol.stat.*;
import org.projectfloodlight.openflow.protocol.oxm.*;
import org.projectfloodlight.openflow.protocol.oxs.*;
import org.projectfloodlight.openflow.protocol.queueprop.*;
import org.projectfloodlight.openflow.types.*;
import org.projectfloodlight.openflow.util.*;
import org.projectfloodlight.openflow.exceptions.*;
import io.netty.buffer.ByteBuf;
import java.util.Set;

abstract class OFTableFeaturePropVer15 {
    // version: 1.5
    final static byte WIRE_VERSION = 6;
    final static int MINIMUM_LENGTH = 4;


    public final static OFTableFeaturePropVer15.Reader READER = new Reader();

    static class Reader implements OFMessageReader<OFTableFeatureProp> {
        @Override
        public OFTableFeatureProp readFrom(ByteBuf bb) throws OFParseError {
            if(bb.readableBytes() < MINIMUM_LENGTH)
                return null;
            int start = bb.readerIndex();
            short type = bb.readShort();
            bb.readerIndex(start);
            switch(type) {
               case (short) 0x6:
                   // discriminator value 0x6=0x6 for class OFTableFeaturePropApplyActionsVer15
                   return OFTableFeaturePropApplyActionsVer15.READER.readFrom(bb);
               case (short) 0x7:
                   // discriminator value 0x7=0x7 for class OFTableFeaturePropApplyActionsMissVer15
                   return OFTableFeaturePropApplyActionsMissVer15.READER.readFrom(bb);
               case (short) 0xe:
                   // discriminator value 0xe=0xe for class OFTableFeaturePropApplySetfieldVer15
                   return OFTableFeaturePropApplySetfieldVer15.READER.readFrom(bb);
               case (short) 0xf:
                   // discriminator value 0xf=0xf for class OFTableFeaturePropApplySetfieldMissVer15
                   return OFTableFeaturePropApplySetfieldMissVer15.READER.readFrom(bb);
               case (short) 0xfffe:
                   // discriminator value 0xfffe=0xfffe for class OFTableFeaturePropExperimenterVer15
                   return OFTableFeaturePropExperimenterVer15.READER.readFrom(bb);
               case (short) 0xffff:
                   // discriminator value 0xffff=0xffff for class OFTableFeaturePropExperimenterMissVer15
                   return OFTableFeaturePropExperimenterMissVer15.READER.readFrom(bb);
               case (short) 0x0:
                   // discriminator value 0x0=0x0 for class OFTableFeaturePropInstructionsVer15
                   return OFTableFeaturePropInstructionsVer15.READER.readFrom(bb);
               case (short) 0x1:
                   // discriminator value 0x1=0x1 for class OFTableFeaturePropInstructionsMissVer15
                   return OFTableFeaturePropInstructionsMissVer15.READER.readFrom(bb);
               case (short) 0x8:
                   // discriminator value 0x8=0x8 for class OFTableFeaturePropMatchVer15
                   return OFTableFeaturePropMatchVer15.READER.readFrom(bb);
               case (short) 0x2:
                   // discriminator value 0x2=0x2 for class OFTableFeaturePropNextTablesVer15
                   return OFTableFeaturePropNextTablesVer15.READER.readFrom(bb);
               case (short) 0x3:
                   // discriminator value 0x3=0x3 for class OFTableFeaturePropNextTablesMissVer15
                   return OFTableFeaturePropNextTablesMissVer15.READER.readFrom(bb);
               case (short) 0xa:
                   // discriminator value 0xa=0xa for class OFTableFeaturePropWildcardsVer15
                   return OFTableFeaturePropWildcardsVer15.READER.readFrom(bb);
               case (short) 0x4:
                   // discriminator value 0x4=0x4 for class OFTableFeaturePropWriteActionsVer15
                   return OFTableFeaturePropWriteActionsVer15.READER.readFrom(bb);
               case (short) 0x5:
                   // discriminator value 0x5=0x5 for class OFTableFeaturePropWriteActionsMissVer15
                   return OFTableFeaturePropWriteActionsMissVer15.READER.readFrom(bb);
               case (short) 0xc:
                   // discriminator value 0xc=0xc for class OFTableFeaturePropWriteSetfieldVer15
                   return OFTableFeaturePropWriteSetfieldVer15.READER.readFrom(bb);
               case (short) 0xd:
                   // discriminator value 0xd=0xd for class OFTableFeaturePropWriteSetfieldMissVer15
                   return OFTableFeaturePropWriteSetfieldMissVer15.READER.readFrom(bb);
               case (short) 0x10:
                   // discriminator value 0x10=0x10 for class OFTableFeaturePropTableSyncFromVer15
                   return OFTableFeaturePropTableSyncFromVer15.READER.readFrom(bb);
               case (short) 0x14:
                   // discriminator value 0x14=0x14 for class OFTableFeaturePropApplyCopyfieldVer15
                   return OFTableFeaturePropApplyCopyfieldVer15.READER.readFrom(bb);
               case (short) 0x15:
                   // discriminator value 0x15=0x15 for class OFTableFeaturePropApplyCopyfieldMissVer15
                   return OFTableFeaturePropApplyCopyfieldMissVer15.READER.readFrom(bb);
               case (short) 0x12:
                   // discriminator value 0x12=0x12 for class OFTableFeaturePropWriteCopyfieldVer15
                   return OFTableFeaturePropWriteCopyfieldVer15.READER.readFrom(bb);
               case (short) 0x13:
                   // discriminator value 0x13=0x13 for class OFTableFeaturePropWriteCopyfieldMissVer15
                   return OFTableFeaturePropWriteCopyfieldMissVer15.READER.readFrom(bb);
               default:
                   throw new OFParseError("Unknown value for discriminator type of class OFTableFeaturePropVer15: " + type);
            }
        }
    }
}
