// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template of_interface.java
// Do not modify

package org.projectfloodlight.openflow.protocol;

import org.projectfloodlight.openflow.protocol.*;
import org.projectfloodlight.openflow.protocol.action.*;
import org.projectfloodlight.openflow.protocol.actionid.*;
import org.projectfloodlight.openflow.protocol.bsntlv.*;
import org.projectfloodlight.openflow.protocol.errormsg.*;
import org.projectfloodlight.openflow.protocol.meterband.*;
import org.projectfloodlight.openflow.protocol.instruction.*;
import org.projectfloodlight.openflow.protocol.instructionid.*;
import org.projectfloodlight.openflow.protocol.match.*;
import org.projectfloodlight.openflow.protocol.stat.*;
import org.projectfloodlight.openflow.protocol.oxm.*;
import org.projectfloodlight.openflow.protocol.oxs.*;
import org.projectfloodlight.openflow.protocol.queueprop.*;
import org.projectfloodlight.openflow.types.*;
import org.projectfloodlight.openflow.util.*;
import org.projectfloodlight.openflow.exceptions.*;
import io.netty.buffer.ByteBuf;

public interface OFBsnLacpStatsEntry extends OFObject {
    int getActorKey();
    int getActorPortNum();
    int getActorPortPriority();
    MacAddress getActorSysMac();
    int getActorSysPriority();
    short getConvergenceStatus();
    int getPartnerKey();
    int getPartnerPortNum();
    int getPartnerPortPriority();
    MacAddress getPartnerSysMac();
    int getPartnerSysPriority();
    OFPort getPortNo();
    OFVersion getVersion();

    void writeTo(ByteBuf channelBuffer);

    Builder createBuilder();
    public interface Builder  {
        OFBsnLacpStatsEntry build();
        int getActorKey();
        Builder setActorKey(int actorKey);
        int getActorPortNum();
        Builder setActorPortNum(int actorPortNum);
        int getActorPortPriority();
        Builder setActorPortPriority(int actorPortPriority);
        MacAddress getActorSysMac();
        Builder setActorSysMac(MacAddress actorSysMac);
        int getActorSysPriority();
        Builder setActorSysPriority(int actorSysPriority);
        short getConvergenceStatus();
        Builder setConvergenceStatus(short convergenceStatus);
        int getPartnerKey();
        Builder setPartnerKey(int partnerKey);
        int getPartnerPortNum();
        Builder setPartnerPortNum(int partnerPortNum);
        int getPartnerPortPriority();
        Builder setPartnerPortPriority(int partnerPortPriority);
        MacAddress getPartnerSysMac();
        Builder setPartnerSysMac(MacAddress partnerSysMac);
        int getPartnerSysPriority();
        Builder setPartnerSysPriority(int partnerSysPriority);
        OFPort getPortNo();
        Builder setPortNo(OFPort portNo);
        OFVersion getVersion();
    }
}
