// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template of_interface.java
// Do not modify

package org.projectfloodlight.openflow.protocol;

import org.projectfloodlight.openflow.protocol.*;
import org.projectfloodlight.openflow.protocol.action.*;
import org.projectfloodlight.openflow.protocol.actionid.*;
import org.projectfloodlight.openflow.protocol.bsntlv.*;
import org.projectfloodlight.openflow.protocol.errormsg.*;
import org.projectfloodlight.openflow.protocol.meterband.*;
import org.projectfloodlight.openflow.protocol.instruction.*;
import org.projectfloodlight.openflow.protocol.instructionid.*;
import org.projectfloodlight.openflow.protocol.match.*;
import org.projectfloodlight.openflow.protocol.stat.*;
import org.projectfloodlight.openflow.protocol.oxm.*;
import org.projectfloodlight.openflow.protocol.oxs.*;
import org.projectfloodlight.openflow.protocol.queueprop.*;
import org.projectfloodlight.openflow.types.*;
import org.projectfloodlight.openflow.util.*;
import org.projectfloodlight.openflow.exceptions.*;
import io.netty.buffer.ByteBuf;

public interface OFPortDescPropOptical extends OFObject, OFPortDescProp {
    long getRxGridFreqLmda();
    long getRxMaxFreqLmda();
    long getRxMinFreqLmda();
    long getSupported();
    long getTxGridFreqLmda();
    long getTxMaxFreqLmda();
    long getTxMinFreqLmda();
    long getTxPwrMax();
    long getTxPwrMin();
    int getType();
    OFVersion getVersion();

    void writeTo(ByteBuf channelBuffer);

    Builder createBuilder();
    public interface Builder extends OFPortDescProp.Builder {
        OFPortDescPropOptical build();
        long getRxGridFreqLmda();
        Builder setRxGridFreqLmda(long rxGridFreqLmda);
        long getRxMaxFreqLmda();
        Builder setRxMaxFreqLmda(long rxMaxFreqLmda);
        long getRxMinFreqLmda();
        Builder setRxMinFreqLmda(long rxMinFreqLmda);
        long getSupported();
        Builder setSupported(long supported);
        long getTxGridFreqLmda();
        Builder setTxGridFreqLmda(long txGridFreqLmda);
        long getTxMaxFreqLmda();
        Builder setTxMaxFreqLmda(long txMaxFreqLmda);
        long getTxMinFreqLmda();
        Builder setTxMinFreqLmda(long txMinFreqLmda);
        long getTxPwrMax();
        Builder setTxPwrMax(long txPwrMax);
        long getTxPwrMin();
        Builder setTxPwrMin(long txPwrMin);
        int getType();
        OFVersion getVersion();
    }
}
